name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Create npm build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
      - name: Create npm tarball (dry-run)
        run: npm pack
