name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Create npm build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
        with:
          verbose: true
      - name: Create npm tarball (dry-run)
        run: npm pack
